### PR TITLE
remove horizon_method slot

### PR DESCRIPTION
**Pull request by bmeluch**
remove horizon_method slot from waterinterface

MAM 2023-09-27: added a link to the issue here:
- #148

### CODE REVIEW

**Review by pkalita-lbl — CHANGES_REQUESTED** [review]
Hey thanks for taking a crack at this! However the submission schema is, for lack of a better word, weird. Specifically, the file you've changed actually gets built based on other files. The file you want to look at is `sheets_and_friends/tsv_in/import_slots_regardless.tsv`. In particular [this line](https://github.com/microbiomedata/submission-schema/blob/7586046a4b3664e310eade51acc5e34f4eaf0ed1/sheets_and_friends/tsv_in/import_slots_regardless.tsv?plain=1#L209) says "take the `horizon_method` slot from the `nmdc_schema` and plop it into the following classes of the `submission_schema`: `AirInterface`, `BiofilmInterface`, etc". So you'd want to remove `WaterInterface` from that list. Then you can regenerate all the generated files (there will be a lot!) and run tests with `make all`.

**Comment by turbomam** [comment]
Thanks @bmeluch !

Let's set up a conversation between you and either @pkalita-lbl or me about "what files to commit" Sorry, I haven't set this repo to be especially helpful in that regard!

You PRs will be easiest to review if you only commit the files you have changed. It looks like you are either doing the build process on your own or at least getting ready for it. That's **great**. 

Please don't commit changes to `examples/output/` or `project/`. In fact, it's unlikely that you will need to commit files from any path other than `src/`.

**Comment by turbomam** [comment]
It also looks like you up-dated the valid data files. That's great too. Please also add a new invalid example file that shows the illegal use of whatever slots/columns you are removing. @pkalita-lbl , @brynnz22 and I can help you with that too.

**Comment by pkalita-lbl** [comment]
> a conversation between you and either @pkalita-lbl or me about "what files to commit"

You know that conversation with me will start with "we should have drastically fewer generated files checked in in the first place" 😂 

> Please also add a new invalid example file that shows the illegal use of whatever slots/columns you are removing

I have mixed feelings about this. I understand what the point would be, but where do we draw the line? It's impractical to test _every_ slot that _shouldn't_ be there.

**Comment by turbomam** [comment]
Thanks @pkalita-lbl. Let me ponder what value I think we're getting out of having the `examples/output` files. I would like for the repo to include a worked example of data being converted between LinkML JSON or YAML, TSV and DH JSON. But I guess what we are checking in now doesn't really help with that.

**Review by pkalita-lbl — APPROVED** [review]

**Comment by bmeluch** [comment]
Thank you so much @pkalita-lbl !
@mslarae13 helpful notes from Patrick about how to edit the submission schema

**Pull request merged**
